---
- name: install prometheus
  hosts: node1
  tasks:
     - name: Install required packages
       apt:
         name: "{{ item }}"
         state: present
       with_items:
     - prometheus
     - prometheus-node-exporter
     - prometheus-alertmanager

     - name: Copy Prometheus configuration file
       copy:
       src: prometheus.yml
       dest: /etc/prometheus/prometheus.yml
       notify:
     - restart prometheus

- name: Restart Prometheus
  hosts: node1
  tasks:
  - name: Restart Prometheus service
    service:
     name: prometheus
     state: restarted
